name: test
on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v4
        with:
          cache: false
          go-version: "1.21"
      - run: make setup-ci-env
      - run: make validate-ci
      - run: make validate
      - run: make test
